Fixing sqlite3.ProgrammingError Thread error.
I have made some changes in order to fix this errors:
>ProgrammingError: SQLite objects created in a thread can only be used in that same thread. 
>The object was created in thread id 140736046805888 and this is thread id 123145314775040.
According to [this answer](https://stackoverflow.com/a/2894830/4683950) on StackOverflow